# This workflow is to automate Checkmarx SCA scans.  It runs on a push to the main branch.
#
# The following GitHub Secrets must be first defined:
#   - CHECKMARX_SCA_USERNAME
#   - CHECKMARX_SCA_PASSWORD
#
# The following variables must be inserted below:
#   - <ProjectName>
#   - <SCATenant>
#   - <GitHubRepoUrl>
#
# For full documentation, including a list of all inputs, please refer to the README https://github.com/checkmarx-ts/checkmarx-cxflow-github-action

name: Checkmarx SCA Scan - CxFlow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkmarx SAST Scan
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.4 # GitHub Action version
      ##uses: n3d4u2c/checkmarx-cxflow-github-action@master #modified to install sbt
      with:
        project: scala3-example-project-git
        team: /CxServer
        checkmarx_url: ${{ secrets.CHECKMARX_URL }} # To be stored in GitHub Secrets.
        checkmarx_username: ${{ secrets.CHECKMARX_USER }} # To be stored in GitHub Secrets.
        checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }} # To be stored in GitHub Secrets.
        checkmarx_client_secret: 014DF517-39D1-4453-B7B3-9930C563627C
        break_build: false
        scanners: sast
        bug_tracker: None
        params: --logging.level.org.springframework.web.client.RestTemplate=TRACE --logging.level.com.checkmarx.flow.service=DEBUG --logging.level.org.apache.http.wire=TRACE --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }} --repo-url="<GitHubRepoUrl>" --cx-flow.filterSeverity --cx-flow.filterCategory
