name: Checkmarx SCA Scan - SCAResolver
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: SCA Resolver
      run: |
          mkdir ${{ github.workspace }}/SCAResolver
          wget "https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-linux64.tar.gz"
          tar -xvf ScaResolver-linux64.tar.gz -C ${{ github.workspace }}/SCAResolver
          ./SCAResolver/ScaResolver -s ${{ github.workspace }} -n scala3-example-project-git -a SCA-Champions -u ${{ secrets.CHECKMARX_SCA_USERNAME }} -p ${{ secrets.CHECKMARX_SCA_TENANT }} --log-level 'Verbose' --report-extension Pdf --report-type Risk --severity-threshold High -u ${{ secrets.CHECKMARX_SCA_USERNAME }} -p ${{ secrets.CHECKMARX_SCA_PASSWORD }} --log-level 'Verbose' --report-extension Pdf --report-type Risk --severity-threshold {Medium:100}
